### ISSUE TITLE
Netconf Build Error

### ISSUE THREAD

**Issue by tylersiemers** [BroadbandForum/yang#13]
Getting the following error when trying to build a NED (via Cisco NSO). 

yang/bbf-l2-forwarding-forwarders@2020-10-13.yang:226: error: the node 'port-groups' from module 'bbf-l2-forwarding' (in node 'forwarder' from 'bbf-l2-forwarding') is not found

I've looked but can't see where port-groups should be found for the 2020-10-13 version.

**Comment by jboyd77** [comment]
That is indeed a bug. The reason it hasn't been caught before now is that the leafref is defined in a grouping that isn't used anywhere in TR-383, so other build tools, e.g. pyang, don't see the error when we validate the models during development and prior to publication.

**Comment by jboyd77** [comment]
Since the grouping isn't used, you can work around this by commenting out the grouping ```forwarder-port-group-state```.

**Comment by tylersiemers** [comment]
Awesome. Thanks for the workaround. I was able to get it built now. I did have to do the same thing on the following file

bbf-fast-availability@2020-10-13.yang:158: error: grouping 'availability-parameters' not found.

**Comment by jboyd77** [comment]
Not sure why you would see an error with bbf-fast-availability. It uses the grouping 'availability' from bbf-availability.yang and that grouping uses 'availability-parameters' also defined in bbf-availability. Line 158 in bbf-fast-availability is also the end of the file so it is a strange place to report an error.

**Comment by tylersiemers** [comment]
I agree. Still trying to find out how Cisco's NSO is trying to build the yangs. They use a custom tool and I am not sure if its using pyang or something else. Anycase commenting out, for now, seems to work until I get more details on how it's reading the yangs to build the ned.
