### ISSUE TITLE
According to G.997.2 the text in brackets must be "INITSFCAUSE"

### ISSUE THREAD

**Issue by mfreudenberger** [BroadbandForum/yang#3]
https://github.com/BroadbandForum/yang/blob/c6c2e1cde670eebb04a755aa664aacd30763f7ef/standard/interface/bbf-fast-line-status-body.yang#L1071

**Comment by wlupton** [comment]
Thanks @mfreudenberger! Given that you are a BBF member, please could you confirm whether [this internal Jira issue](https://issues.broadband-forum.org/browse/YMDPU-263) is the same? If not, it would be great if you could create a new internal BBF Jira issue in the YMDPU project!

**Comment by mfreudenberger** [comment]
Hi William, yes confirmed.  Thanks Markus.

**Comment by wlupton** [comment]
Thanks. I'll close this issue.
