### ISSUE TITLE
The correct reference to G.997.2 is clause 7.14.2.1 (LINK-STATE)

### ISSUE THREAD

**Issue by mfreudenberger** [BroadbandForum/yang#4]
https://github.com/BroadbandForum/yang/blob/c6c2e1cde670eebb04a755aa664aacd30763f7ef/standard/interface/bbf-fast-line-status-body.yang#L1018

**Comment by jboyd77** [comment]
I agree this should be fixed. Please create a [Jira](https://issues.broadband-forum.org/projects/YMDPU/issues/YMDPU-189?filter=allopenissues) in the YMDPU project. We are also in straw ballot on WT-355 Amendment 2 so it would be great if you would take a critical look at the models and make straw ballot comments as necessary. Here's a link to the [wiki page](https://wiki.broadband-forum.org/display/BBF/WT-355+Amendment+2+Straw+Ballot) with the details.

**Comment by mfreudenberger** [comment]
@jboyd77  Jira is created [https://issues.broadband-forum.org/projects/YMDPU/issues/YMDPU-264?filter=allopenissues&orderby=created+DESC%2C+priority+DESC%2C+updated+DESC](url)

**Comment by mfreudenberger** [comment]
@jboyd77: Jira is created (YMDPU-264).

**Comment by wlupton** [comment]
Thanks. I'll close this issue.
